version: '3'

services:
  webserver:
    image: 'nginx:latest'
    working_dir: /symfogram/public
    volumes:
      - '.:/symfogram'
      - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '80:80'
    depends_on:
      - database
      - redis
    networks:
      - sail

  php-fpm:
    build: phpdocker/php-fpm
    working_dir: /symfogram
    volumes:
      - '.:/symfogram'
      - './phpdocker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini'
      - './phpdocker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
    environment:
      - PHP_IDE_CONFIG=serverName=localhost
    networks:
      - sail

  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-symfogram}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - '5432:5432'
    networks:
      - sail

  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    restart: always
    volumes:
      - redis:/data
#      - /etc/localtime:/etc/localtime:ro
    networks:
      - sail


networks:
  sail:
    driver: bridge
volumes:
  db-data:
  redis:
#  redis-data:
#  redis.conf:

