# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.avatar_pictures_directory: '%kernel.project_dir%/public/uploads/avatar_pictures/'
    app.post_pictures_directory: '%kernel.project_dir%/public/uploads/post_pictures/'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    Predis\Client:
        class: Predis\Client
#        arguments:
#            - { url: '%env(REDIS_URL)%' }
        arguments:
            - host: '%env(REDIS_HOST)%'
            - port: '%env(REDIS_PORT)%'

    App\Service\Uploaders\AvatarPictureUploader:
        arguments:
            $targetDirectory: '%app.avatar_pictures_directory%'

    App\Service\Uploaders\PostPictureUploader:
        arguments:
            $targetDirectory: '%app.post_pictures_directory%'

    App\Service\Subscription:
        arguments:
            $redis: '@Predis\Client'
            $security: '@Symfony\Component\Security\Core\Security'
